version: "3"
services:
  smarthome_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  smarthome_frontend:
    build:
      context: ./robonomics-smarthome-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
